spring:
  application:
  name: expense-tracker-api

  datasource:
    url: jdbc:postgresql://localhost:5433/expense_tracker_db
    password: postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop # Cria as entidades do banco de dados automaticamente e deleta quando o programa é finalizado
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  security:
    token:
      secret: D9UpFveHLp4xGFN56GdMHwFoucu63mxT